# Appendix

## Comparison of outliers and inliers
This sections includes some pivot tables with summary counts for further analysis.

In [ ]:
df[['knn_outlier_inlier', 'if_outlier_inlier']].value_counts().reset_index()

  knn_outlier_inlier if_outlier_inlier  count
0             Inlier            Inlier   9883
1            Outlier           Outlier     51
2             Inlier           Outlier     49
3            Outlier            Inlier     17

In [ ]:
df['Inlier_outlier_group'].value_counts().reset_index()

    Inlier_outlier_group  count
0            both_Inlier   9883
1           both_Outlier     51
2  knn_inlier_if_Outlier     49
3  knn_Outlier_if_inlier     17

In [147]:
output = df.groupby('Inlier_outlier_group').agg(
    {'viewing_frequency':['mean', 'median', 'std', 'min', 'max'],
     'viewing_time_seconds':['mean', 'median', 'std', 'min', 'max']}    
    )

In [152]:
output.columns = ['_'.join(col).strip() for col in output.columns.values]
output.reset_index(inplace=True)

In [149]:
output

,Inlier_outlier_group,viewing_frequency_mean,viewing_frequency_median,viewing_frequency_std,viewing_frequency_min,viewing_frequency_max,viewing_time_seconds_mean,viewing_time_seconds_median,viewing_time_seconds_std,viewing_time_seconds_min,viewing_time_seconds_max
0,both_Inlier,10.515047,10.48,5.491851,1.00,19.99,43236.801886,43197.81,24958.326635,14.74,86395.19
1,both_Outlier,10.841897,11.87,5.669284,1.02,19.99,41868.962241,44293.39,26142.637040,258.35,86184.71
2,knn_Outlier_if_inlier,8.529231,7.78,5.512867,1.05,16.04,43705.736154,44362.26,19931.302845,4427.40,81038.12
3,knn_inlier_if_Outlier,12.634048,13.30,5.389881,2.07,19.76,45520.877381,50280.93,28993.334125,139.39,85915.90

In [156]:
# Standardized z-score for viewing frequency column
display(df['viewing_frequency'].apply(lambda x: (x - df['viewing_frequency'].mean()) / df['viewing_frequency'].std()).round(2))

0      -1.44
1       0.38
2       1.24
3       0.11
4      -0.92
        ...
9995    0.19
9996   -0.60
9997    0.47
9998    1.04
9999   -0.05
Name: viewing_frequency, Length: 10000, dtype: float64

# APPENDIX

## TO ADD
- Python Data Cleaning, p.124 - 5 -> Shapiro - Wilk test
- Add the criteria of max_total_amount in the README file